version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: doacin-db
    environment:
      POSTGRES_USER: doacin_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doacin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doacin-net

volumes:
  postgres_data:

networks:
  doacin-net:
    driver: bridge
