version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: doacin-db
    environment:
      POSTGRES_USER: doacin_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doacin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doacin-net

  postgres-test:
    image: postgres:16-alpine
    container_name: doacin-db-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: doacin_test
    ports:
      - "5433:5432"  # Porta diferente para n√£o conflitar
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - doacin-net

volumes:
  postgres_data:
  postgres_test_data:

networks:
  doacin-net:
    driver: bridge
